name: logohunter
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.7
  - keras=2.2.4
  - tensorflow-gpu
  - opencv=3.4.4
  - matplotlib=3.1.1
  - flask=1.1.1
  - pillow=6.1.0
  - scikit-learn=0.21.3
  - pip:
      - flask_bootstrap
